# Your Name or Company
title: Ariella Cheskis-Gold

# Description of your website. This is used for social sharing.
description:  The beautiful website of qa master, project manager, and reddit enthusiast Ariella Cheskis-Gold.

# A brief blurb about yourself
content: I am a totally curious, creative, clever rockstar who is a nerd interested in the intersection of media, technology, and creative culture. I have many years of experience working as a Project Manager in the Digital Space for Websites, Landing Pages, Ad Units, and online branding experiences. I have a passion for programming and love to learn new things. You can find me baking desserts, listening to a random genre of music and watching foreign tv (with subtitles!).

# Add your social links
social:
  - platform: github
    url: https://github.com/ariellacg
  - platform: linkedin
    url: https://www.linkedin.com/in/ariellacheskisgold/

# General settings
# url: http://brianmaierjr.github.com/uni
# baseurl: "/uni" 
markdown: kramdown
sharing_image: share.jpg
google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
